import 'package:flutter/material.dart';
import 'package:vat_appeal_bot/utils/theme.dart' as theme;


class TermsPage extends StatelessWidget {
  const TermsPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 1150.0,
      padding: const EdgeInsets.all(16.0),
      decoration: BoxDecoration(
        color: theme.bgPrimaryColor,
        borderRadius: theme.borderRadius,
        border: Border.all(
          color: theme.borderColor,
          width: theme.borderWidth,
        ),
      ),
      child: const Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Text(
            "Terms & Conditions",
            style: TextStyle(
              fontSize: 20.0,
              color: theme.textPrimaryColor,
              fontWeight: FontWeight.bold,
            ),
          ),
          SizedBox(height: 8.0),
          Text(
            "Please read these terms and conditions carefully before using the VAT Appeal Bot web app (the “app”). "
            "By using the app, you agree to be bound by these terms and conditions. If you do not agree to these terms and conditions, please do not use the app.",
            style: TextStyle(
              fontSize: 16.0,
              color: theme.textSecondaryColor,
            ),
          ),
          SizedBox(height: 16.0),
          Text(
            "Eligibility",
            style: TextStyle(
              fontSize: 16.0,
              color: theme.textPrimaryColor,
              fontWeight: FontWeight.bold,
            ),
          ),
          SizedBox(height: 8.0),
          Text(
            "The app is intended for the exclusive use of the employees of PwC Czech Republic who are part of the Tax & Legal team. "
            "You agree to notify us immediately of any unauthorized use of the app or any other breach of security.",
            style: TextStyle(
              fontSize: 16.0,
              color: theme.textSecondaryColor,
            ),
          ),
          SizedBox(height: 16.0),
          Text(
            "Use of the app",
            style: TextStyle(
              fontSize: 16.0,
              color: theme.textPrimaryColor,
              fontWeight: FontWeight.bold,
            ),
          ),
          SizedBox(height: 8.0),
          Text(
            "The app is a tool that helps you to generate a response email for your clients based on a received notice. The app does not provide legal or tax advice, and you should not rely on the app as a substitute for professional judgment. "
            "You are solely responsible for reviewing and editing the generated email before sending it to your client. You agree to use the app in accordance with all applicable laws and regulations, and in a manner that does not infringe the rights of any third party.",
            style: TextStyle(
              fontSize: 16.0,
              color: theme.textSecondaryColor,
            ),
          ),
          SizedBox(height: 16.0),
          Text(
            "Disclaimer of warranties and limitation of liability",
            style: TextStyle(
              fontSize: 16.0,
              color: theme.textPrimaryColor,
              fontWeight: FontWeight.bold,
            ),
          ),
          SizedBox(height: 8.0),
          Text(
            "The app is provided on an “as is” and “as available” basis, without any warranties of any kind, either express or implied. "
            "We do not warrant that the app will be uninterrupted, error-free, secure, accurate, complete or up-to-date. We do not guarantee that the app will meet your requirements or expectations, or that the results generated by the app will be suitable for your purposes. We are not liable for any direct, indirect, incidental, consequential or punitive damages arising out of or in connection with your use of or inability to use the app, even if we have been advised of the possibility of such damages.",
            style: TextStyle(
              fontSize: 16.0,
              color: theme.textSecondaryColor,
            ),
          ),
          SizedBox(height: 16.0),
          Text(
            "Changes to these terms and conditions",
            style: TextStyle(
              fontSize: 16.0,
              color: theme.textPrimaryColor,
              fontWeight: FontWeight.bold,
            ),
          ),
          SizedBox(height: 8.0),
          Text(
            "We reserve the right to modify these terms and conditions at any time and without prior notice. You should check this page periodically to review the current terms and conditions. "
            "Your continued use of the app after any changes constitutes your acceptance of the new terms and conditions.",
            style: TextStyle(
              fontSize: 16.0,
              color: theme.textSecondaryColor,
            ),
          ),
          SizedBox(height: 16.0),
          Text(
            "Contact us",
            style: TextStyle(
              fontSize: 16.0,
              color: theme.textPrimaryColor,
              fontWeight: FontWeight.bold,
            ),
          ),
          SizedBox(height: 8.0),
          Text(
            "If you have any questions or concerns about these terms and conditions, "
            "please contact the Technology Consulting Digital Strategy community at PwC Czech Republic.",
            style: TextStyle(
              fontSize: 16.0,
              color: theme.textSecondaryColor,
            ),
          ),
        ],
      ),
    );
  }
}
